### ISSUE TITLE
[TEST] Venue/Banner/Sale 테스트 코드

### ISSUE THREAD

**Issue by dolee2403** [S-C-S-D/ICTicket-BackEnd#107]
## 🛠 Issue

 Venue/Banner/Sale 테스트 코드 작성
## 📝 To-do

- [ ] Venue 테스트 코드
- [ ] Banner 테스트 코드
- [ ] Sale 테스트 코드
