### ISSUE TITLE
[Test] User,Session,Comment,Like 테스트코드

### ISSUE THREAD

**Issue by hangeunhyeong** [S-C-S-D/ICTicket-BackEnd#108]
## 🛠 Issue

user,session,comment,like 테스트코드
## 📝 To-do

- [ ] user controller test
- [ ] user service test
- [ ] session controller test
- [ ] session service test
- [ ] comment controller test
- [ ] comment service test
- [ ] RedisConfig dev에 올릴때 password 주석처리 해제
