### ISSUE TITLE
[FEATURE] [admin] 공연

### ISSUE THREAD

**Issue by dolee2403** [S-C-S-D/ICTicket-BackEnd#22]
## 🛠 Issue

관리자가 사용하는 공연기
## 📝 To-do

- [ ] performance 공연 등록
- [ ] performance 공연 수정
- [ ] performance 공연 삭제
