### ISSUE TITLE
[Fix] user/sales/seat

### ISSUE THREAD

**Issue by Lee0zoo** [S-C-S-D/ICTicket-BackEnd#41]
## 🛠 Issue

예외처리 수정, 코드 수정

## 📝 To-do

- [x] 회원 탈퇴 시 토큰 ""으로 변경
- [x] 할인 정보가 있는 공연에 대한 추가 할인 적용 예외 추가
- [x] 좌석 번호 중복 예외처리(Grade 별)
- [x] 좌석 상태 Enumrate 추가
