### ISSUE TITLE
[FEATURE] 공연 생성 

### ISSUE THREAD

**Issue by dolee2403** [S-C-S-D/ICTicket-BackEnd#6]
## 🛠 Issue

공연 CRUD
## 📝 To-do

- [x] performance 단일 공연 조회
- [ ] performance 장르별 공연 랭킹 조회
- [ ] performance 오늘 오픈 공연 조회
- [ ] performance 추천 티켓 조회
- [ ] performance 할인 중인 공연 조회
- [ ] performance 오픈 예정 공연 조회
- [ ] performance 전체 랭킹 조회
