### ISSUE TITLE
[REFACTOR] 코드 정리 

### ISSUE THREAD

**Issue by jay1261** [S-C-S-D/ICTicket-BackEnd#71]
## 🛠 Issue

코드 정리
## 📝 To-do

- [x] AdminPerformanceService 74 ; 지우기
- [x] AdminSeatService에 User loginUser 사용 물어보기
- [x] AdminSessionService 에 69, 71, 72, 73, 94, 사용 물어보기, 159, 163 코드 물어보기
- [x] Dto에 final 사용여부
- [x] ExceptionDto 에서 19번 줄 쓰나요?
- [x] ExceptionManager에서 39줄 IOException 이거 쓰나요?
- [x] Config 패키지는 아직 구현 안한거였죠?
- [x] LikeService에 20번줄 필요한가요?
- [x] Order에 setter 필요한가요?
- [x] OrderRepositoryQueryImpl에 19 em 사용하나요?
- [x] Seat에 setter 필요한가요?
- [x] SessionRepository에서 17, 19, 28 다 쓴다고 했었죠??
- [x] OrderAndSeatQueryDto 필요한가요?
- [x] UserSignupRequestDto에서 {1,} 를 +로 써도 된다는데 왜 그런가요?
