### ISSUE TITLE
[Refactor] Comment,Session 리팩토링

### ISSUE THREAD

**Issue by hangeunhyeong** [S-C-S-D/ICTicket-BackEnd#84]
## 🛠 Issue

comment, session에 대한 리팩토링 작업

## 📝 To-do

- [x] querydsl 자바독 : 주제 @param @description
- [x] controller 자바독 : 주제 @param @return
- [x] service 자바독 : controller 관련 메서드는 controller와 동일하게, 그 외 메서드는 주제 @param @description
- [x] repository 자바독 : 단순 주석처리
- [x] entity 관련 검증 로직은 entity 쪽 메서드로 따로 빼기
